[package]
name = "expr-druid-1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#druid = "0.7.0"  # << Causes E0277 error
druid = { git = "https://github.com/linebender/druid.git" }
